### ISSUE TITLE
Generated Cards

### ISSUE THREAD

**Issue by Jerry-licious** [casey-c/DeckSummary#3]
In the game, there are multiple ways to generate cards, namely:
* Adding a random card to your hand directly (infernal blade, white noise, distraction, foreign influence and discovery).
* Adding multiple random cards to your hand directly (jack of all trades+, transmutation).
* Adding cards to your hand every turn (hello world, magnetism, creative AI).
* Adding *specific* cards to your hand every turn (carve reality and deceive reality).

The first type of card generation can typically be ignored, as they are just really random and they don't give any, card advantage anyways. 
However, the second type of card generation is a bit special as it can give you card advantage. This *can* be simply counted as draw, though it may be confusing - as players want to subtract the total draw from their total deck size to see how well they cycle: adding this variable pollutes the value. Should there be a specific counter to this, or should they just be ignored?
The third type of card generation is a bit tricky as well, these powers essentially give you a card every turn, should this be counted as draw, or are powers stinky and should just be ignored?
The fourth type of card generation is relatively simple, since the specific card is already known, the effectiveness of the generated card can just be added to their main card.

**Comment by casey-c** [comment]
My votes:
1. ignore (too random)
2. ignore (too random)
3. ignore (too random)
4. include 

I think you have similar views to me on this one - I think it would just be a losing battle if we tried to quantify a lot of the randomness on our own instead of just letting the player figure it all out for how they see it best.

**Comment by Jerry-licious** [comment]
Done.
